name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the React app
        run: npm run build

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactapp:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs after the build job

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}  # Your server's IP
          username: ${{ secrets.SSH_USER }}  # Your server username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/reactapp:latest
            
            # Stop and remove the old container if it exists
            docker stop reactapp || true
            docker rm reactapp || true
            
            # Run the new container
            docker run -d -p 80:80 --name reactapp ${{ secrets.DOCKER_USERNAME }}/reactapp:latest
